# Written by sub_transition on Mon Jun 22 17:20:54 2026.
skip_non_dialogue=no
skip_immediately=no
start_enabled=yes
notifications=no
pause_on_start=no
pause_before_end=no
hide_subs_when_playing=no
start_delay=0
reset_before=1
min_duration=0.4
normal_speed=1
inter_speed=1
menu_font_size=12
